name: devel
on:
  push:
    branches:
      - 'main'
    paths:
      - 'dockerfiles/**/*'
jobs:
  devcontainer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - working-directory: ./dockerfiles
        run: |
          set -e
          IMAGE_NAME="openspot_node:dev"
          IMAGE_REPOSITORY="$(echo "ghcr.io/${{ github.repository_owner }}/${IMAGE_NAME}" | tr '[:upper:]' '[:lower:]')"
          docker build -t "${IMAGE_REPOSITORY}" -f devel.Dockerfile .
          # Push image to GitHub Container Registry
          echo "${{ github.token }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
          docker push "${IMAGE_REPOSITORY}"
