name: release

on:
  release:
    types:
      - published

jobs:
  deploycontainer:
    name: build deploy image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - working-directory: ./dockerfiles
        run: |
          set -e
          IMAGE_NAME="openspot_node:deploy-${{ github.ref_name }}"
          IMAGE_REPOSITORY="$(echo "ghcr.io/${{ github.repository_owner }}/${IMAGE_NAME}" | tr '[:upper:]' '[:lower:]')"
          docker build -t "${IMAGE_REPOSITORY}" -f deploy.Dockerfile --build-arg GH_REF=${{ github.ref }} .
          # Push image to GitHub Container Registry
          echo "${{ github.token }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
          docker push "${IMAGE_REPOSITORY}"
